### ISSUE TITLE
Error when running HMMRATAC

### ISSUE THREAD

**Issue by amitjavilaventura** [LiuLabUB/HMMRATAC#19]
When I run HMMRATAC with my sorted.bam file it gives me an error.

```
Exception in thread "main" java.util.InputMismatchException
        at java.util.Scanner.throwFor(Scanner.java:864)
        at java.util.Scanner.next(Scanner.java:1485)
        at java.util.Scanner.nextInt(Scanner.java:2117)
        at java.util.Scanner.nextInt(Scanner.java:2076)
        at GenomeFileReaders.GenomeFileReader.<init>(GenomeFileReader.java:48)
```

The code I use is the following one:
```
java -jar HMMRATAC_V1.2.5_exe.jar \
--bam bamfiles/${sample}/${sample}_.bam \
--index bamfiles/${sample}/${sample}_.bam.bai \
--genome genome.info \
--output ${trial}/results/hmmr/${sample}/${sample} \
--upper 20 \
--lower 10 \
--peaks True \
```

The `genome.info` file contains the names and sizes of the chromosomes of the `mm9` mouse genome. This is what the file says:

```
chr1 197195432
chr2	181748087
chr3 159599783
chr4	155630120
chr5	152537259
chr6 149517037
chr7	152524553
chr8 131738871
chr9 124076172
chr10 129993255
chr11 121843856
chr12 121257530
chr13 120284312
chr14 125194864
chr15 103494974
chr16 98319150
chr17 95272651
chr18 90772031
chr19 61342430
chrX 166650296
chrY 15902555
chrM 16299
chr13_random	400311
chr16_random	3994
chr17_random 628739
chr1_random 1231697
chr3_random 41899
chr4_random 160594
chr5_random 357350
chr7_random 362490
chr8_random 849593
chr9_random 449403
chrUn_random 5900358
chrX_random 1785075
chrY_random 58682461
```
Could someone give me some advice, please?

Thank you.

**Comment by EvanTarbell** [comment]
Thanks for using our tool!
It looks like there are a mixture of spaces and tabs separating the two columns. Can you confirm that they are all tabs? And let me know if that does anything.

**Comment by amitjavilaventura** [comment]
Yes, they were all tabs. It was when I wrote the text in the issue that I changed it to make it "prettier". 

By the way, I solved it. The problem was that I wrote headers in each column.

**Comment by EvanTarbell** [comment]
OK perfect!!
