### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by hhvu0102** [LiuLabUB/HMMRATAC#29]
Hi,

I'm trying to run HMMRATAC but had this error:

`Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.base/java.util.TimSort.mergeLo(TimSort.java:777)
        at java.base/java.util.TimSort.mergeAt(TimSort.java:514)
        at java.base/java.util.TimSort.mergeCollapse(TimSort.java:441)
        at java.base/java.util.TimSort.sort(TimSort.java:245)
        at java.base/java.util.Arrays.sort(Arrays.java:1514)
        at java.base/java.util.ArrayList.sort(ArrayList.java:1585)
        at java.base/java.util.Collections.sort(Collections.java:176)
        at HMMR_ATAC.SubtractBed.subtract(SubtractBed.java:131)
        at HMMR_ATAC.SubtractBed.<init>(SubtractBed.java:42)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:465)
`

After merging my replicates and sorting the merged file, I ran this command:
`java -jar ~/HMMRATAC_V1.2.8_exe.jar -b /path/to/atac.forHMMRATAC.bam -i /path/to/atac.forHMMRATAC.bam.bai -g /path/to/mm9.size  -e /path/to/blacklist.bed`

My genome file is:

> chr1    197195432
> chr2    181748087
> chr3    159599783
> chr4    155630120
> chr5    152537259
> chr6    149517037
> chr7    152524553
> chr8    131738871
> chr9    124076172
> chr10   129993255
> chr11   121843856
> chr12   121257530
> chr13   120284312
> chr14   125194864
> chr15   103494974
> chr16   98319150
> chr17   95272651
> chr18   90772031
> chr19   61342430
> chrX    166650296
> chrY    15902555
> chrM    16299

Thank you for your help!

**Comment by EvanTarbell** [comment]
Looks like it is a bug in my comparator function for sorting the intervals. That code is subtracting the excluded regions (ie  blacklisted sites) from the training set, but is incomplete, especially for cases where the start sites are equal.  Looking at it now, I'm surprised that it hasn't come up before.  I'll fix it and release a new version soon, which should take care of that error.

**Comment by hhvu0102** [comment]
Thanks! Looking forward to trying out the new version :)

**Comment by EvanTarbell** [comment]
Version 12.9 should solve this issue. Let me know if it does!

**Comment by hhvu0102** [comment]
It worked. Thanks!
