### ISSUE TITLE
java.io.FileNotFoundException: (Too many open files) error

### ISSUE THREAD

**Issue by sudarshanchari** [LiuLabUB/HMMRATAC#4]
Hi,
Hope you are doing well. I am trying to run HMMRATAC and it starts/ runs initially without any issues. It creates the model and starts with viterbi algorithm. But soon after that, it stops and throws up what I think is a "too many open files" error. I was just wondering if this is a known issue for you and/ or if I need to add other options to my java usage. The actual usage command and error message are below.

I am running this on a cluster and hope that the open file limit is not a problem ( for me, ulimit -n 1024). If this is a potential issue then I would need to request more from the admin.

Please let me know, when you get a chance.

Thanks and Warm Regards,
Sudarshan.

**Usage**
java -jar HMMRATAC_V1.0_exe.jar 
-b file.bam
-i file.bai 
-g genomefile.txt 
-w file.bigwig 
--bedgraph true
--bgscore true 
-o file_hmmratac

**Actual error**
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)   
   
Caused by: java.io.FileNotFoundException:file.bigwig (Too many open files) 
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.broad.tribble.util.SeekableFileStream.<init>(SeekableFileStream.java:40)
        at org.broad.igv.bbfile.BBFileReader.<init>(BBFileReader.java:127)
        at HMMR_ATAC.GetSignal.find(GetSignal.java:72)
        at HMMR_ATAC.GetSignal.<init>(GetSignal.java:40)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:417)
        ... 5 more

**Comment by EvanTarbell** [comment]
Is the bigwig file being used by another program at the same time? HMMRATAC, in an effort to save memory, does not store the information from any of the input files. Instead, it reads them as needed. So if more than one program is trying to read the same files at the same time, it may cause an error.  That could be the issue.

**Comment by sudarshanchari** [comment]
No. The bigwig is only being used by HMMRATAC. I have no other program running except for HMMRATAC.

**Comment by sudarshanchari** [comment]
Hi,
Thanks a tonne for your reply. I did ask the admin. to increase my open file limit and he increased it 4X (i.e. ulimit -n 4096). Additionally, I split the bam and bigwig by chromosomes and it gives me the same error. So I am assuming that file size is not an issue.

I apologize, but did not mention earlier I am working with _D.melanogaster_ ATAC-seq data and not human. I assume this should not influence HMMRATAC completion if all the input files are correctly generated as per the guide.

Thanks and Warm Regards,
SC

**Comment by EvanTarbell** [comment]
We are going to test HMMRATAC on the cluster we have here at UB. We have only tested it on our server and our personal computers.  

It is possible that the java runtime environment on your cluster has its own file limit, that may need to be changed.  
You can also try running it on your actual computer. I'd recommend doing it by chromosome and setting the --window option to around 1/10th of the default.  IE 2500000.  
I will get back to you as soon as we figure this out.  
Thanks in advance for your patience

**Comment by hmyh1202** [comment]
How to generate bigwig file, and what is  the requirement for that file ?

**Comment by EvanTarbell** [comment]
I have uploaded a shell script, Make_HMMR_Files.sh, which will create the required input files for HMMRATAC, including the bigWig file.

**Comment by hmyh1202** [comment]
Many thanks!
However, why you use --keep-dup all in macs2 calling?

**Comment by mcjmigdal** [comment]
Hi, @EvanTarbell I've run into the same problem, so far I didn't manage to check if changing ulimits would solve the issue; it sure look like one way to go for the time being. 

However it looks to me like there is an issue with closing some open handles to files. I'm not writing in Java but if you look into file `HMMR_ATAC.GetSignal`, `wigReader = null;` doesn't seem like a proper way to close file opened by `BBFileReader wigReader = new BBFileReader(wig);`

Hope it helps, I could try to play with it myself but I have no idea how to compile it :)

Cheers

**Comment by EvanTarbell** [comment]
Thanks for the comment.  After some debugging, we have determined that the issue you mention is the problem here.  The BBFileReader class (which is a third party class for reading BigWig files) doesn't have a dedicated and proper close() method.  This doesn't seem to cause many problems when running on a server or personal computer but causes this error almost every time its run on a cluster.  I am currently testing a version of HMMRATAC that generates its own signal data directly from the read information in order to eliminate the requirement for a bigwig file.  This should solve both the current issue, and make HMMRATAC easier to run, by reducing the amount of pre-processing that a user is required to do.  We should have this version up and ready for download within the next week or two.

**Comment by EvanTarbell** [comment]
Issue is corrected with versions 1.2 and higher.
