### ISSUE TITLE
Q: The shifted bam reads from ATACseqQC are unable to call the peaks. 

### ISSUE THREAD

**Issue by RadPa** [LiuLabUB/HMMRATAC#46]
**Use case**
A clear and concise description of what the use case is. For example: my data is from [...]

**Describe the problem**
A clear and concise description of what happend.

**Describe the solution you tried**
A clear and concise description of any solutions you've tried.

**Additional context**
Add any other context or screenshots about your use case here.

**Comment by EvanTarbell** [comment]
What that error is saying is that the matirx that HMMRATAC uses to hold the separated ATAC-seq fragments (short, mono, di etc) is empty. When i have encountered this in the past, it tends to be some minor formatting error. For instance, it can be caused if the BAM file contains reads mapping to "chr1" while the genome file names the chromosome as "1" or "I" instead of "chr1".

**Comment by RadPa** [comment]
Thank you. I remember changing the bam header.  Good Day

**Comment by EvanTarbell** [comment]
No problem!! Happy to help!!

**Comment by jeffhsu3** [comment]
Does HMMRATAC still work when BAM reads have been stripped of sequence and base qualities such as that produced by deepTools alignmentSieve?

**Comment by EvanTarbell** [comment]
HMMRATAC doesn't use either the sequence or the individual base qualities at any point (it does use the overall mapping quality score though). It should work as long as the samtools package, that i use to read the BAM file, can still recognize it.

**Comment by jeffhsu3** [comment]
Samtools view seems to work fine on the shifted bam but this is the error I am getting: 
`Exception in thread "main" net.sf.samtools.SAMFormatException: SAM validation error: ERROR: Record 1, Read name SRR7942734.58148285, Zero-length read without FZ, CS or CQ tag
        at net.sf.samtools.SAMUtils.processValidationErrors(SAMUtils.java:448)
        at net.sf.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:541)
        at net.sf.samtools.BAMFileReader$BAMFileIndexIterator.<init>(BAMFileReader.java:648)
        at net.sf.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:598)
        at net.sf.samtools.BAMFileReader.query(BAMFileReader.java:352)
        at net.sf.samtools.SAMFileReader.query(SAMFileReader.java:363)
        at HMMR_ATAC.pullLargeLengths.read(pullLargeLengths.java:112)
        at HMMR_ATAC.pullLargeLengths.<init>(pullLargeLengths.java:61)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:219)
`
