### ISSUE TITLE
memory error with 40GB RAM and 3.2 GB alignment file

### ISSUE THREAD

**Issue by kzkedzierska** [LiuLabUB/HMMRATAC#48]
Hi, 

I tried running HMMRATAC. Unfortunately, it's not going great. Execution time is quite long and on top of that, the command seems to be throwing the memory error. I have secured 40GB of RAM for this process, and I'm running it on the 3.2GB alignment file. I reduced the window size but still was given this error. I am using 1.2.9 version.

How much memory do I have to provide and what is the expected run time of the algorithm? 

```
$ HMMRATAC --bam ../../alignment/filtered/XXX.bam --index ../../alignment/filtered/XXX.bam.bai --genome /ref/hg38_sizes.genome --blacklist /ref/blacklisted/hg38.blacklist.bed --bedgraph true --output XXX --window 25000 |& tee ../../logs/hmmratac_XXX.log
0Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:261)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
        at java.util.ArrayList.add(ArrayList.java:458)
        at WigMath.pileup.toBedGraph(pileup.java:214)
        at WigMath.pileup.build(pileup.java:205)
        at WigMath.pileup.<init>(pileup.java:70)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:270)
```

**Comment by kzkedzierska** [comment]
ok, this is entirely my bad, I run the HMMRATAC through the conda command which basically translated to `java -Xms512m -Xmx1g`; should be better now.

Sorry ;)
