### ISSUE TITLE
Q: negative standard deviation

### ISSUE THREAD

**Issue by DNAcastigator** [LiuLabUB/HMMRATAC#51]
**Use case**
Hello, I'm analysing some ATAC seq from different tissue and different samples of 5 instar butterflies. For some of the file the tool works properly but for some reason with others don't.

**Describe the problem**
the error I'm getting is this:
#################################
Exception in thread "main" org.apache.commons.math3.exception.NotStrictlyPositiveException: standard deviation (-3.722)
        at org.apache.commons.math3.distribution.NormalDistribution.<init>(NormalDistribution.java:142)
        at org.apache.commons.math3.distribution.NormalDistribution.<init>(NormalDistribution.java:107)
        at org.apache.commons.math3.distribution.NormalDistribution.<init>(NormalDistribution.java:85)
        at GEMM.HMMR_EM.getWeightedDensity(HMMR_EM.java:170)
        at GEMM.HMMR_EM.iterate(HMMR_EM.java:74)
        at GEMM.HMMR_EM.learn(HMMR_EM.java:113)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:228) 
##########################
the reference genome (and chromosome size) is the same for all the data.

**Describe the solution you tried**
Previously I got the same error when I was using the wrong size file but in this situation the size is the same that worked for other samples.

**Comment by EvanTarbell** [comment]
Can you generate a fragment length distribution plot for these datasets? Part of me suspects that there might be datasets with an incomplete fragment distribution, which is causing a negative standard deviation. If this is the case, you could use the --trim option to remove the higher order signals from the analysis. Alternatively, it is possible to skip the EM step all together and instead utilize the parameters generated in successful runs. But the fragment distribution will help diagnose the problem

**Comment by DNAcastigator** [comment]
[LB20.pdf](https://github.com/LiuLabUB/HMMRATAC/files/4366527/LB20.pdf)
[LB21.pdf](https://github.com/LiuLabUB/HMMRATAC/files/4366528/LB21.pdf)
[LB27.pdf](https://github.com/LiuLabUB/HMMRATAC/files/4366529/LB27.pdf)
[LB28.pdf](https://github.com/LiuLabUB/HMMRATAC/files/4366530/LB28.pdf)
[LB29.pdf](https://github.com/LiuLabUB/HMMRATAC/files/4366531/LB29.pdf)
[LB30.pdf](https://github.com/LiuLabUB/HMMRATAC/files/4366532/LB30.pdf)
Thank you for the answer.
Not all the plots seem perfect but unfortunately the use of --trim 3/2/1 didn't solve the problem

**Comment by EvanTarbell** [comment]
Which of the samples are failing and which ones succeed? and can you attach the log files that are generated?

**Comment by DNAcastigator** [comment]
[E3_FW.pdf](https://github.com/LiuLabUB/HMMRATAC/files/4370338/E3_FW.pdf)
[E3_HW.pdf](https://github.com/LiuLabUB/HMMRATAC/files/4370339/E3_HW.pdf)
[E4-FW.pdf](https://github.com/LiuLabUB/HMMRATAC/files/4370340/E4-FW.pdf)
[E3_FW.log](https://github.com/LiuLabUB/HMMRATAC/files/4370342/E3_FW.log)
[E3_HW.log](https://github.com/LiuLabUB/HMMRATAC/files/4370343/E3_HW.log)
[E3HW.log](https://github.com/LiuLabUB/HMMRATAC/files/4370344/E3HW.log)
[E3HW2.log](https://github.com/LiuLabUB/HMMRATAC/files/4370345/E3HW2.log)
[E4-FW.log](https://github.com/LiuLabUB/HMMRATAC/files/4370346/E4-FW.log)
[FW-pboy.log](https://github.com/LiuLabUB/HMMRATAC/files/4370347/FW-pboy.log)
[LB_20.log](https://github.com/LiuLabUB/HMMRATAC/files/4370348/LB_20.log)
[LB_21.log](https://github.com/LiuLabUB/HMMRATAC/files/4370349/LB_21.log)
[LB_27.log](https://github.com/LiuLabUB/HMMRATAC/files/4370350/LB_27.log)
OK so, the files in the previous post are all from failed analysis, here you can find the pdf from successuful analysed files and the log file generate from the succesful analysis and some of the failed one.

**Comment by EvanTarbell** [comment]
So I still think that --trim would solve this problem but it turns out that i dont apply the procedure until after the EM step (ie after the error you are getting). I will work on releasing a new version which applies the --trim option to EM step as well, which should solve your problem. In the meantime, you could take the EM parameters from your successful runs and pass them into HMMR using -m and -s and setting -f False. If they are all from the same organism, this is a reasonable approximation

**Comment by DNAcastigator** [comment]
perfect, many thanks for the help, I will try this last option while waiting for the next update.

**Comment by JihedC** [comment]
Hello,

Was this update released? I have the same problem.

**Comment by angelosarmen** [comment]
Hi,

I'm having the same problem as well. Is a fix going to be released soon?

**Comment by angelosarmen** [comment]
Hi,

I'm having the same problem as well.
