### ISSUE TITLE
Issues using HMMRATAC

### ISSUE THREAD

**Issue by sarkinside** [LiuLabUB/HMMRATAC#6]
Hi, 

First, this is a very interesting paper, congratulation!

I tried to used it by writing the following command: 
 java -jar /Applications/bioinfo_tools/HMMRATAC-master/HMMRATAC_V1.0_exe.jar 
 -b BAM_FILE.bam -i BAM_FILE.bam.bai -g dm6.genome -w BIGWIG_FILE.bw --bedgraph true --bgscore true -o file_hmmratac

Note that the bam has been obtain using bowtie2+samtools, and has been sorted.

However, instantaneously, I obtain the following error message:

_Exception in thread "main" java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: net/sf/samtools/SAMFormatException
at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:165)
... 5 more
Caused by: java.lang.ClassNotFoundException: net.sf.samtools.SAMFormatException
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
... 6 more_

Do you have any idea of the problem here ? 

Thank you very much,

Version of Java:
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

Version of samtools:
samtools 1.8

**Comment by EvanTarbell** [comment]
It appears that this issue is related to how we build and package samtools into HMMRATAC (not the samtools that is installed on your machine, but instead the version that is packaged with HMMRATAC).  And how that build is effected by changes in java versions.  We will address this issue ASAP. In the meantime, we have extensively tested HMMRATAC on Open-JDK1.7 and Oracle's 1.8 versions (SE Runtime Env 1.8). You can run HMMRATAC using java 7 or 8 and it should work. And thank you for bringing this issue to our attention.

**Comment by sarkinside** [comment]
[Update]
Thanks for answering EvanTarbell.

The issue was _"the version of java. Should be java7 or 8, due to the version of Samtools packaged into HMMRATAC code."_ 
EvanTarbell said that this issue will be fixed soon.

I had Java10 and just following the command line on the [Java website](https://www.java.com/en/download/help/mac_uninstall_java.xml) to uninstall java didn't work for me. Java10 was still the display version when typing:
java -version 


What I had to do:
#Download java8 (need [Homebrew](https://brew.sh)):
brew tap caskroom/versions
brew cask install java8
#Remove Java 10
cd /Library/Java/JavaVirtualMachines
sudo rm -rf jdk-10.0.1.jdk
#Now you should have:
java -version
>java version "1.8.0_172"
>Java(TM) SE Runtime Environment (build 1.8.0_172-b11)

Thank a lot,

**Comment by EvanTarbell** [comment]
It seems like the way we packaged samtools (and the other third party sources that HMMRATAC uses) was the problem. We have repackaged them into HMMRATAC and are currently testing it on different versions of Java, including the Open-JDK-1.7, SE Runtime Env. 1.8 and SE 10. We will make this version available soon.
