### ISSUE TITLE
Q: Troobleshooting with Java

### ISSUE THREAD

**Issue by El-Castor** [LiuLabUB/HMMRATAC#61]
**Use case**
Hi, Thanks a lot for you soft it is very interresting. I am working on plants, i'm trying to analyse my ATACseq data. 

**Describe the problem**
When I try tro launch HMMRATAC in order to build the model with the following command : 

```bash 
HMMRATAC -b ${bam} -i ${bamIndex} -g $chromSize -o ${outHMMdir}/${outputFileName} --minlen $minLenOCR --score $scoreType --modelonly $modelOnlyOption
```
with this params:

```
minLenOCR="200"
scoreType="all"
modelOnlyOption="True"
```

I hav ethis error message from JAVA : 

```bash
Exception in thread "main" net.sf.samtools.util.RuntimeIOException: /NetScratch/cpichot/ATACseq_analysis/ATACseq_cytometrie_dec2019_flowers_FMH_rep4_100K/HMMAtac/HMMAtac_peaksCalling/merged_bam_file (est un dossier)
	at net.sf.samtools.AbstractBAMFileIndex$MemoryMappedFileBuffer.<init>(AbstractBAMFileIndex.java:487)
	at net.sf.samtools.AbstractBAMFileIndex.<init>(AbstractBAMFileIndex.java:83)
	at net.sf.samtools.DiskBasedBAMFileIndex.<init>(DiskBasedBAMFileIndex.java:46)
	at net.sf.samtools.BAMFileReader.getIndex(BAMFileReader.java:232)
	at net.sf.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:592)
	at net.sf.samtools.BAMFileReader.query(BAMFileReader.java:352)
	at net.sf.samtools.SAMFileReader.query(SAMFileReader.java:363)
	at HMMR_ATAC.pullLargeLengths.read(pullLargeLengths.java:112)
	at HMMR_ATAC.pullLargeLengths.<init>(pullLargeLengths.java:61)
	at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:219)
Caused by: java.io.FileNotFoundException: /NetScratch/cpichot/ATACseq_analysis/ATACseq_cytometrie_dec2019_flowers_FMH_rep4_100K/HMMAtac/HMMAtac_peaksCalling/merged_bam_file (est un dossier)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at net.sf.samtools.AbstractBAMFileIndex$MemoryMappedFileBuffer.<init>(AbstractBAMFileIndex.java:480)
	... 9 more
```
Do you know what is the issue ?

NOTES: I have merged and sort my bam file using samtool ssoftware as describe on your documentation.

**Describe the solution you tried**
I found any solution yet.

Thanks in Advance.

**Comment by EvanTarbell** [comment]
This error indicates that the program can't find the requested BAM file. Can you check to make sure it is in the correct directory and that the name is correct, with no spaces in the name?

**Comment by El-Castor** [comment]
Hi @EvanTarbell,
Thanks a lot for your response, sorry I have do a mistake. It work fine now.

But I have a new error. It seems like an out of memory as you can see below (100Go of ram). I have try with chromosome separated file but I have the same error. 
see bellow the error : 

```bash
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:242)
	at java.base/java.util.ArrayList.add(ArrayList.java:485)
	at java.base/java.util.ArrayList.add(ArrayList.java:498)
	at WigMath.pileup.toBedGraph(pileup.java:215)
	at WigMath.pileup.build(pileup.java:206)
	at WigMath.pileup.<init>(pileup.java:71)
	at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:270)
```

Do you have any suggestion ?
