### ISSUE TITLE
Keep getting "OutOfMemoryError" even after reducing window size

### ISSUE THREAD

**Issue by nyuhic** [LiuLabUB/HMMRATAC#64]
Hello,

I am trying to run the program on relatively large bam files of ~20gb each and my job always terminates with the error :"main" java.lang.OutOfMemoryError: GC overhead limit exceeded

As mentioned in the troubleshooting guide I have tried reducing the window size to 2.5bm, 1.5mb and 1mb but I still get the issue. I am running the job on a cluster (memory allocation of 100gb) and not my desktop so I dont think resources are an issue. Should I reduce the window size even more?

Since the large 20gb bam files have been produced by merging three replicates, I can try running the program on the smaller individual bam files for each replicate but I am not sure how I will merge the results if I do this. I am interested in making heatmaps of nfr/mononucleosomal fragments so I dont know if merging the resulting bedgraphs would be a good idea or not.

Thanks

The command I am running:
HMMRATAC -b wt.bam -i wt.bam.bai -o wt -g genome.info --window 1000000 --removeDuplicates false -e blacklist.v2.bed --bedgraph true

Here is the error log:
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at net.sf.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:378)
        at net.sf.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:365)
        at net.sf.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:113)
        at net.sf.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:238)
        at java.io.DataInputStream.read(DataInputStream.java:149)
        at net.sf.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:394)
        at net.sf.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:371)

For a second file, I get a similar but longer error message:
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at net.sf.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:378)
        at net.sf.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:365)
        at net.sf.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:113)
        at net.sf.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:238)
        at java.io.DataInputStream.read(DataInputStream.java:149)
        at net.sf.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:394)
        at net.sf.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:371)
        at net.sf.samtools.util.BinaryCodec.readByteBuffer(BinaryCodec.java:480)
        at net.sf.samtools.util.BinaryCodec.readInt(BinaryCodec.java:491)
        at net.sf.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:178)
        at net.sf.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:558)
        at net.sf.samtools.BAMFileReader$BAMFileIndexIterator.getNextRecord(BAMFileReader.java:665)
        at net.sf.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:532)
        at net.sf.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:522)
        at net.sf.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:481)
        at net.sf.samtools.BAMFileReader$BAMQueryFilteringIterator.advance(BAMFileReader.java:750)
        at net.sf.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:720)
        at net.sf.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:673)
        at net.sf.samtools.SAMFileReader$AssertableIterator.next(SAMFileReader.java:672)
        at net.sf.samtools.SAMFileReader$AssertableIterator.next(SAMFileReader.java:650)
        at HMMR_ATAC.pullLargeLengths.read(pullLargeLengths.java:116)
        at HMMR_ATAC.pullLargeLengths.<init>(pullLargeLengths.java:61)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:219)

**Comment by EvanTarbell** [comment]
So what appears to be happening is that when HMMRATAC is sampling the reads in order to identify the optimal parameters for the multimodal distribution, it is running into problems due to too many reads. I have a workaround in there, to only sample 10% os the reads for the process, but with the large file, it seems like that isnt enough for you. I have to work the code a little in order to allow that downsampling to be a user input (so people like you with extra large files can downsample below 10% if needed). 
However, i do think i have a good work around for you. If you provide a genome file containing only one chromosome (say chr1), the it will sample only from that chromosome and build a model with only that data. Once the model is created, you can re-run HMMRATAC, with the previously generated model (passed in with --model) , the full genome file, and some non default options. Set -f False, set -m to the means listed in the log file and -s to the standard deviations listed in the log file. 
In this way, you are building the model and distributions with only chr1 data, but then decoding the genome with that model. I will also work on updating the code allowing for larger files to be processed fully.

**Comment by nyuhic** [comment]
Thanks. I also tried running the program on a single replicate (~8gb bam file) and it still failed. 

I will try to make the model using one chromosome and report back.

**Comment by EvanTarbell** [comment]
Its possible, considering you are running it on a cluster, that the memory allocation might not be set correctly. Check out issue #57 and see if those suggestions help with your issue as well. It might not be necessary to limit it to one chromosome if that is the cause of your issue.

**Comment by nyuhic** [comment]
Thanks. I am running with a single chromosome right now. 

Also I looked at issue #57  which was solved by allocating memory to the program using the command -Xmx 200G -jar HMMRATAC_V1.2.10_exe.jar.  I am just a bit confused how to use the -Xmx command as I installed the program with conda. Should I search for the jar file in the conda environment and then run it with that file?

**Comment by EvanTarbell** [comment]
After looking at issue #48 i am pretty sure that is the problem. I think you could add the -Xmx option after HMMRATAC on the command line, but to be honest, i have never run it via conda. You could always download the official release from the release tab on this GitHub page and run it like: 
`java -Xmx200G -jar HMMRATAC_V1.2.10_exe.jar ...`

**Comment by nyuhic** [comment]
You are probably right because I ran the program with one chromosome and it made it past the point where it calculated the means in the log file but failed at the next step even with only one chromosome:

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at FormatConverters.PileupToBedGraph.generateGraph2(PileupToBedGraph.java:86)
        at FormatConverters.PileupToBedGraph.run(PileupToBedGraph.java:53)
        at FormatConverters.PileupToBedGraph.<init>(PileupToBedGraph.java:41)
        at WigMath.pileup.toBedGraph(pileup.java:217)
        at WigMath.pileup.build(pileup.java:206)
        at WigMath.pileup.<init>(pileup.java:71)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:270)

I will try to download and run it without conda with the correct memory allocation.

**Comment by nyuhic** [comment]
Just to update I was able to complete the run on one of the smaller samples (the bigger samples are still running) by allocating 100gb using the command java -Xmx100G -jar. When the program is installed through conda, the default memory allocated is very small so it might be a good idea to mention in the readme/guide file to use the Xmx command with conda installations. Also the jar to be used with the command is present in one of the sub folders of the conda environment location. 

Before you close the issue I have one more question. If I run the program with --bgscore true, will the score added to the bedgraph be what I specify using the --score parameter or is this parameter only for peak calling? And which score type would you recommend for comparing signal between two treatment conditions. 

Thanks

**Comment by EvanTarbell** [comment]
Yes, the --score option is what is outputted with the --bgscore option. Of the score options that we allow, only 'max' has been extensively tested. That is the score type that we used in the paper, for instance. So i usually recommend using that option. As for comparing two conditions, I have a question. Are you looking to do differential accessibility analysis? If so, check out issues #40 and #53. If you aren't looking to do such a formal analysis, than i would probably recommend comparing the zscore or fold change scores. I say this because both of these scoring methods account for background signal, which could muddy the results when using a unnormalized score like 'max' or 'mean' etc.

**Comment by nyuhic** [comment]
Thanks, For differential accessibility I was pretty much planning to do what you have described in the other issues (not with Diffbind but with a similar Deseq2 based pipeline).  

But I am also interested in nucleosome occupancy analysis for which I was asking about the score parameter.  For comparing nucleosome occupancy between conditions, I am not sure how I can use package like diffbind so I was thinking of just extracting the nucleosomal signal from the bedgraph and then plotting it around regions of interest in two different conditions to see if I can visually see any differences. So for this z-score or fold-change would probably be better?

**Comment by EvanTarbell** [comment]
Yes, i believe that zscore or fold-change would be better scoring options for that type of analysis, because they account for background. You should be able to use the 'all' option as well with --bgscore. I have a few bugs to fix related to that option, but that should only effect peak calls, not the bedgraph.

**Comment by nyuhic** [comment]
So is it better to not use the peak files generated will the 'all' option and just repeat the analysis separately with default settings for calling peaks?

**Comment by EvanTarbell** [comment]
Yes. No peaks will be outputted with the 'all' option because of the bugs. The bug is related to the --threshold option (because 'all' results in a score that is a string of characters, an error will occur when it tries to filter the peaks based on a double --threshold value). This bug is referenced in issue #52 and is on my to do list. The issue is only related to peak outputs and wont affect anything else. As i mentioned above, when restarting to get the peaks, use the --model, -f, -m and -s options to skip over the fragment EM and model building procedures (as you have already done them with the first run). This will speed up the peak calling process. Also, keep in mind that the --bgscore option adds considerable time to the program. So it will take longer than it otherwise would

**Comment by nyuhic** [comment]
Great. Thanks!

**Comment by nyuhic** [comment]
Just commenting to report a possible bug. As you mentioned the peak file is not generated properly when the --score parameter is set to 'all' but the bedgraph should work fine. I ran the command with --score set to 'all' and the bedgraphs generated for all samples had less than 10 lines so this option probably also interferes with the bedgraph generation.  Setting the --score parameter to zscore solved the issue and produced complete bedgraphs.

**Comment by EvanTarbell** [comment]
Thanks! I created a new issue for that as well.
