### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jimcdonald** [LiuLabUB/HMMRATAC#8]
Evan,

I have run HMMRATAC v1.2, on 7 cell lines. It appears to have worked on 5 of them, but 2 of them produced errors which prevented the production of any output. The errors are the following, and are consistent across all 4 individual samples I have for each cell line:

For the Hey cell line:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 14
        at HMMR_ATAC.ArgParser.set(ArgParser.java:228)
        at HMMR_ATAC.ArgParser.<init>(ArgParser.java:44)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:74)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 18
        at HMMR_ATAC.ArgParser.set(ArgParser.java:228)
        at HMMR_ATAC.ArgParser.<init>(ArgParser.java:44)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:74)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 18
        at HMMR_ATAC.ArgParser.set(ArgParser.java:228)
        at HMMR_ATAC.ArgParser.<init>(ArgParser.java:44)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:74)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 18
        at HMMR_ATAC.ArgParser.set(ArgParser.java:228)
        at HMMR_ATAC.ArgParser.<init>(ArgParser.java:44)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:74)

For the Kuramochi cell line:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 14
        at HMMR_ATAC.ArgParser.set(ArgParser.java:212)
        at HMMR_ATAC.ArgParser.<init>(ArgParser.java:44)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:74)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 18
        at HMMR_ATAC.ArgParser.set(ArgParser.java:212)
        at HMMR_ATAC.ArgParser.<init>(ArgParser.java:44)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:74)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 18
        at HMMR_ATAC.ArgParser.set(ArgParser.java:212)
        at HMMR_ATAC.ArgParser.<init>(ArgParser.java:44)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:74)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 18
        at HMMR_ATAC.ArgParser.set(ArgParser.java:212)
        at HMMR_ATAC.ArgParser.<init>(ArgParser.java:44)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:74)

The only difference between the two is: at HMMR_ATAC.ArgParser.set(ArgParser.java:228) vs at HMMR_ATAC.ArgParser.set(ArgParser.java:212).

I tried to track down the issue by digging around in the source code zip file for the release. If the (ArgParser.java:XXX) numbers are line numbers, then I think the subroutine is passed an incorrect set of files as line 44 of ArgParser.java deals with receiving the strings passed by the main program.

**What confuses me is that the script I am using to submit the jobs to the SLURM job manager has the exact same inputs for all the cell lines.** All I do is change the name of the directory in each script but the commands are all the same (see below).

An example of this code follows:
#!/bin/bash

#SBATCH -o HMMR.v1.2.TykNu.ATACseq.library001.treat1.mock.%j.out # File for STD OUT
#SBATCH -e HMMR.v1.2.TykNu.ATACseq.library001.treat1.mock.%j.err # File for STD ERR
#SBATCH -p defq # Node queue to submit to
#SBATCH -N 1 # Number of nodes to reserve
#SBATCH -D /lustre/groups/chiappinellilab/processed_data/ATACseq.bowtie2 # Path to working directory
#SBATCH -J HMMR.v1.2.TykNu.ATACseq.library001.treat1.mock # Job TykNu.ATACseq.library001.treat1.mock
#SBATCH --export=NONE # Don't export my environmental variables to this job
#SBATCH -t 2-00:00:00 # Time to reserve
#SBATCH --nice=100 # Niceness value

ml jdk/1.7.0
d=TykNu.ATACseq.library001.treat1.mock
java -jar /groups/chiappinellilab/software/executables/HMMRATAC_V1.2_exe.jar -m 75,200,400,600 --bedgraph true -o ${d}/${d}.HMMRv1.2.u-10.l-02 -b ${d}/*.sorted.bam -i ${d}/*.sorted.bam.bai -g /groups/chiappinellilab/genomes/hg38/ucsc.analysisSet/hg38.analysisSet.chroms.sizes -w ${d}/*.bw
java -jar /groups/chiappinellilab/software/executables/HMMRATAC_V1.2_exe.jar -m 75,200,400,600 --bedgraph true -u 20 -l 10 -o ${d}/${d}.HMMRv1.2.u-20.l-10 -b ${d}/*.sorted.bam -i ${d}/*.sorted.bam.bai -g /groups/chiappinellilab/genomes/hg38/ucsc.analysisSet/hg38.analysisSet.chroms.sizes -w ${d}/*.bw
java -jar /groups/chiappinellilab/software/executables/HMMRATAC_V1.2_exe.jar -m 75,200,400,600 --bedgraph true -u 40 -l 20 -o ${d}/${d}.HMMRv1.2.u-40.l-20 -b ${d}/*.sorted.bam -i ${d}/*.sorted.bam.bai -g /groups/chiappinellilab/genomes/hg38/ucsc.analysisSet/hg38.analysisSet.chroms.sizes -w ${d}/*.bw
java -jar /groups/chiappinellilab/software/executables/HMMRATAC_V1.2_exe.jar -m 75,200,400,600 --bedgraph true -u 30 -l 10 -o ${d}/${d}.HMMRv1.2.u-30.l-10 -b ${d}/*.sorted.bam -i ${d}/*.sorted.bam.bai -g /groups/chiappinellilab/genomes/hg38/ucsc.analysisSet/hg38.analysisSet.chroms.sizes -w ${d}/*.bw

Do you have any ideas why the script would be inconsistently giving this error?

In the meantime, I'll move forward with the cell lines I do have data for. Thank you for fixing the "too many files" exception!

**Comment by EvanTarbell** [comment]
You mention that the only difference is the name of the directory containing your input files. I have a question: is the second letter of either directory name an "e" or an "u".  And is the set that throws "HMMR_ATAC.ArgParser.set(ArgParser.java:228)" error have the "e" and the one that throws the "HMMR_ATAC.ArgParser.set(ArgParser.java:212)" error have the "u"?

**Comment by jimcdonald** [comment]
Yes. You are right completely. The directories start with the cell line name. The Hey cells give the 228 error and the 2nd letter is "e". Similarly, the Kuramochi samples give the 212 error and the 2nd letter is "u".

Does your question imply that simply by changing the directory names, I can make HMMRATAC work for those samples? What would cause such an oddly specific issue where only certain 2nd letters are rejected?

**Comment by jimcdonald** [comment]
Also just for your reference, the other cell lines are: A2780, A549, H1299, H23, and TykNu. The directories for those lines also start with their cell line names and they work just fine.

**Comment by jimcdonald** [comment]
Oh, I think I see -- the ArgParser.java script cases are triggering this. I will just try changing the 2nd letter please let me know if you have another solution in mind and I'll let you know if it works. Thanks for your help!

**Comment by EvanTarbell** [comment]
version 1.2.1 has corrected this

**Comment by jimcdonald** [comment]
Thanks for your quick response on this and for immediately fixing it with a new release!
