### ISSUE TITLE
BR: Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read 

### ISSUE THREAD

**Issue by JihedC** [LiuLabUB/HMMRATAC#80]
**Describe the bug**
Dear @EvanTarbell and @taoliu, thank you for hmmratac. It seems to be working well in most case but not for me so far.
I want to perform peak calling with paired-end data but so far I only get the error message 

` Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read`

**To Reproduce**
I have tried to perform HMMRATAC peak calling with my own dataset. Since it didn't work I tried with the test dataset you used in the publication SRR891269 to SRR891274.
I mapped the reads using bowtie2 to the human genome, and prepared an index file for every bam files.
I also prepared a `genome.info`.
I have installed HMMRATAC using a condo environment in order to have everything within a Snakemake pipeline.

I got for my dataset and the published dataset the same error message 

```
Activating conda environment: /exports/humgen/Jianhui/Snakemake_ATAC_2020/ATAC-seq_pipeline/human_data/Snakemake_ATAC_2020/ATAC-seq_pipeline/.snakemake/conda/a0dc6185 

Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read 

        at net.sf.samtools.SAMRecord.requireReadPaired(SAMRecord.java:675) 

        at net.sf.samtools.SAMRecord.getMateUnmappedFlag(SAMRecord.java:702) 

        at HMMR_ATAC.pullLargeLengths.read(pullLargeLengths.java:122) 

        at HMMR_ATAC.pullLargeLengths.<init>(pullLargeLengths.java:61) 

        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:219) 

```

**Expected behavior**

Peak calling in the human dataset just like published. Production of bed files.

**Screenshots**

<img width="1059" alt="Capture d’écran 2020-12-07 à 11 04 53" src="https://user-images.githubusercontent.com/22910541/101337558-1a1adb80-387c-11eb-8599-42b9c0144a21.png">

**System (please complete the following information):**

Conda environment with hmmratac 1.2.10

If you have any ideas that could help me solve this problem it would be great!

Thanks! 

Jihed

**Comment by JihedC** [comment]
I managed to solve the issue.
I have just added the argument `--no-mixed` to my bowtie2 alignment command.
