### ISSUE TITLE
Q: Error when using bedgraph option： Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by jamesc99** [LiuLabUB/HMMRATAC#91]
Hey, I am using hmmr and I encountered some problems. when I use the default syntax (java -jar HMMRATAC_V1.2.4_exe.jar -b ATACseq.sorted.bam -i ATACseq.sorted.bam.bai -g genome.info), it works good. but when I add a --bedgraph option to it (java -jar HMMRATAC_V1.2.4_exe.jar -b ATACseq.sorted.bam -i ATACseq.sorted.bam.bai -g genome.info --bedgraph), I will get error below:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 7
        at HMMR_ATAC.ArgParser.set(ArgParser.java:383)
        at HMMR_ATAC.ArgParser.<init>(ArgParser.java:70)
        at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:104)

I dont know why and I would be really appreciate if you have any idea. thanks

**Comment by EvanTarbell** [comment]
You have to put the word "True" after --bedgraph. ie:
`java -jar HMMRATAC_V1.2.4_exe.jar -b ATACseq.sorted.bam -i ATACseq.sorted.bam.bai -g genome.info --bedgraph True`
--bedgraph isnt a "flag" option, so the argument parser (which is throwing the error) is expecting something after it. 
Hope this helps
